# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model: 
#    + IONet
#    + descriptor upsampling 
#    + cross-border keypoints
#    + descriptor loss

model:
    params:
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
arch:
    epochs: 60 # 50 from original, then 10 more
datasets:
    train:
        path: "/data/datasets/keypoint_export/"
pretrained_model: "/data/experiments/kp2d/KeypointNetwithIOLoss_07_30_2021__08_33_21/model.ckpt"


wandb:
    dry_run: True
    project: "kp2d"
    project: os.environ.get("WANDB_PROJECT", "")  # Wandb project
    entity: os.environ.get("WANDB_ENTITY", "")    # Wandb entity
    tags: []                                      # Wandb tags
    dir: './'                                       # Wandb save folder
